export const featuredProducts = [
  {
    id: 1,
    sectorCode: "13000000",
    name: "جل معقم لليدين من 50 مل -1000 مل -رمز اعتماد1000",
    productCode: "13991000",
    sectorName: "المستلزمات الطبية",
    definition: "جل معقم",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "المستلزمات الطبية - 13000000",
    subcategory: "جل معقم لليدين من 50 مل -1000 مل -رمز اعتماد1000 - 13991000",
    priceType: "Aqustiable",
    imageUrl: "/13991000.png",
    factories: [
      {
        id: "saudi-mais-medical-consumables",
        name: "Saudi Mais Medical Consumables",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "saudi-pharmaceutical-industries",
        name: "الشركة السعودية للصناعات الصيدلانية",
        address: "Unnamed Road, 15312, المدينة الصناعية الجديدة, السعودية",
        contactNumber: "0",
        email: "logistics@saudi-pharma.net",
        hasBaseLine: false,
      },
      {
        id: "national-pharmaceutical-factory",
        name: "شركة مصنع الأدوية الوطني",
        address: "4111, المدينة الصناعية الجديدة",
        contactNumber: "4649850",
        email: "metab.alenezi@nationalpharma.com",
        hasBaseLine: false,
      },
      {
        id: "hemam-wataneya-for-industry",
        name: "مصنع همم وطنية للصناعة",
        address: "المدينة الصناعية بالخرج",
        contactNumber: "0506414045",
        email: "zaid4045@gamil.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 2,
    sectorCode: "13000000",
    name: "بخاخ مطهر من 120 مل - 1000 مل- رمز اعتماد (1001)",
    productCode: "13991001",
    sectorName: "المستلزمات الطبية",
    definition: "مطهر",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "المستلزمات الطبية - 13000000",
    subcategory: "بخاخ مطهر من 120 مل - 1000 مل- رمز اعتماد (1001) - 13991001",
    priceType: "Aqustiable",
    imageUrl: "/13991001.png",
    factories: [
      {
        id: "hemam-wataneya-for-industry",
        name: "مصنع همم وطنية للصناعة",
        address: "المدينة الصناعية بالخرج",
        contactNumber: "506414045",
        email: "zaid4045@gamil.com",
        hasBaseLine: false,
      },
      {
        id: "national-pharmaceutical-factory",
        name: "شركة مصنع الأدوية الوطني",
        address: "4111, المدينة الصناعية الجديدة",
        contactNumber: "4649850",
        email: "metab.alenezi@nationalpharma.com",
        hasBaseLine: false,
      },
      {
        id: "gulf-care-factory",
        name: "مصنع عناية الخليج للصناعة",
        address: "8276, المدينة الصناعية بصبيرة",
        contactNumber: "2382615",
        email: "drananzeh@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-pharmaceutical-industries",
        name: "الشركة السعودية للصناعات الصيدلانية",
        address: "Unnamed Road, 15312, السعودية",
        contactNumber: "0",
        email: "logistics@saudi-pharma.net",
        hasBaseLine: false,
      },
      {
        id: "hemam-wataneya-for-industry-2",
        name: "مصنع همم وطنية للصناعة",
        address: "المدينة الصناعية بالخرج",
        contactNumber: "506414045",
        email: "zaid4045@gamil.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 3,
    sectorCode: "11000000",
    name: "وصلات ميكانية",
    productCode: "11002190",
    sectorName: "البناء والتشييد",
    definition:
      "وصلات غالقة منكمشة بالحرارة، تستخدم في توصيل الكلابلات الكهربائية مع بعضها البعض",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 24/6/2025",
    category: "البناء والتشييد - 11000000",
    subcategory: "وصلات ميكانية - 11002190",
    priceType: "Aqustiable",
    imageUrl: "/11002190.png",
    factories: [
      {
        id: "erga-fertilizers-ltd",
        name: "شركة ايرقا لصناعة الأسمدة المحدودة",
        address: "منطقة الرياض",
        contactNumber: "966559777667",
        email: "Ahmeda@aljardan.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 4,
    sectorCode: "16000000",
    sectorCode: "16000000",
    name: "ملطف جو – رمز اعتماد 3006",
    productCode: "16473006",
    sectorName: "مستهلكات النظافة",
    definition:
      "معطرات الجو هي منتجات استهلاكية تنبعث منها رائحة عطرية. هذا البند يشمل: - المواد العطرية/النفاثة المستخدمة في تلطيف الجو",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "مستهلكات النظافة - 16000000",
    subcategory: "ملطف جو – رمز اعتماد 3006 - 16473006",
    priceType: "Aqustiable",
    imageUrl: "/16473006.png",
    factories: [
      {
        id: "karnaf-chemical-products-factory",
        name: "مصنع كرنف للمنتجات الكيميائيه",
        address: "منطقة الرياض",
        contactNumber: "966505588800",
        email: "karnaffactory@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "reza-investment-co-ltd",
        name: "شركة رضا للاستثمار المحدودة",
        address: "المدينة الصناعية، جدة",
        contactNumber: "966551021729",
        email: "sanjaya@rezagroup.com",
        hasBaseLine: false,
      },
      {
        id: "zain-industries-one-person-company",
        name: "شركة زين للصناعات شركة شخص واحد",
        address: "المنطقة الشرقية - الجبيل",
        contactNumber: "966591279211",
        email: "alfiah.a@zainindustries.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-energy-materials-production-co-factory",
        name: "مصنع الشركة السعودية لإنتاج مواد الطاقة",
        address: "المدينة الصناعية الثانية، 3616",
        contactNumber: "138166777",
        email: "gyr@sidco.com.sa",
        hasBaseLine: false,
      },
      {
        id: "rich-taste-perfumes-co",
        name: "شركة المذاق الغني للعطور",
        address: "5181, مكة 24227, السعودية",
        contactNumber: "52023000",
        email: "abuzeyad_1408@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "precious-fragrance-manufacturing-co",
        name: "شركة العطر النفيس للتصنيع",
        address: "المدينة الصناعية الثالثة بجدة",
        contactNumber: "0",
        email: "precious.fragrance2020@gmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 5,
    sectorCode: "17000000",
    name: "مذيب دهان",
    productCode: "17006020",
    sectorName: "المواد الكيميائية و الأسمدة",
    definition: "منتج كيميائي يستخدم في اذابة الدهان الخارجي للسيارات وغيرها",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "المواد الكيميائية و الأسمدة - 17000000",
    subcategory: "مذيب دهان - 17006020",
    priceType: "Aqustiable",
    imageUrl: "/17006020.jpg",
    factories: [
      {
        id: "makkah-paints",
        name: "شركة مكة للدهانات",
        address: "منطقة مكة المكرمة",
        contactNumber: "966555566270",
        email: "OMAR@AKA.COM.SA",
        hasBaseLine: false,
      },
      {
        id: "lemon-industrial",
        name: "مصنع شركة سيجما السعودية للدهانات المحدودة",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "dammam-gates",
        name: "مصنع بوابة الدمام للدهانات",
        address: "المنطقة الشرقية",
        contactNumber: "966505178923",
        email: "h.dgf@hotmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 6,
    sectorCode: "17000000",
    name: "طلاء الايبوكسي المطابق",
    productCode: "17006025",
    sectorName: "المواد الكيميائية و الأسمدة",
    definition: "لا يوجد",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 1 سبتمبر 2025",
    category: "المواد الكيميائية و الأسمدة - 17000000",
    subcategory: "طلاء الايبوكسي المطابق - 17006025",
    priceType: "Aqustiable",
    imageUrl: "/17006025.jpg",
    factories: [
      {
        id: "arabian-pipe-coating",
        name: "Arabian Pipe Coating Company",
        address: "****",
        contactNumber: "966",
        email: "****",
        hasBaseLine: false,
      },
      {
        id: "apco-coating-eastern",
        name: "فرع الشركة العربية لتغليف الأنابيب",
        address: "المنطقة الشرقية",
        contactNumber: "966560043098",
        email: "mababneh@apco-coating.com",
        hasBaseLine: false,
      },
      {
        id: "khodair-pipes",
        name: "وحدة إطلاق أنابيب الأسلاك الكهربائية",
        address: "المنطقة الشرقية",
        contactNumber: "966541520859",
        email: "mohammed.al-khodair@s3c....",
        hasBaseLine: false,
      },
      {
        id: "oriental-coatings",
        name: "... إطلاق الشرق للدهانات والعلاجات",
        address: "منطقة الرياض",
        contactNumber: "966504441840",
        email: "suul97@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "tamyeez-chemicals",
        name: "مصنع ريبون للكيماويات",
        address: "المنطقة الشرقية",
        contactNumber: "966505856268",
        email: "abdullah@tamyeez.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 7,
    sectorCode: "23000000",
    name: "ورق لدفاتر تدوين الملاحظات",
    productCode: "23003209",
    sectorName: "القرطاسية والأدوات المكتبية",
    definition:
      "هو كتاب خالٍ من الكتابة يستخدم لتسجيل الملاحظات والمذكرات وللدراسة ويشمل الكتابة والرسم",
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "القرطاسية والأدوات المكتبية - 23000000",
    subcategory: "ورق لدفاتر تدوين الملاحظات - 23003209",
    priceType: "Aqustiable",
    imageUrl: "/23003209.png",
    factories: [
      {
        id: "al-fanniya-plastics-steco",
        name: "الشركة الفنية للبلاستيك المحدودة ( ستيكو )",
        address: "منطقة الرياض",
        contactNumber: "966505413704",
        email: "salimkhodr@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "aljawad-carton-packaging",
        name: "مصنع الجواد للكرتون والتغليف",
        address: "المنطقة الشرقية",
        contactNumber: "966556662985",
        email: "jho.dev@aljawadgroup.net",
        hasBaseLine: false,
      },
      {
        id: "retal-packaging",
        name: "شركة رتال للتغليف",
        address: "منطقة الرياض",
        contactNumber: "966583355098",
        email: "m.amgad@obeikan.com.sa",
        hasBaseLine: false,
      },
      {
        id: "marina-united-paper-products",
        name: "شركة مارينا المتحدة للمنتجات الورقية والتغليف",
        address: "منطقة الرياض",
        contactNumber: "580808031",
        email: "nasserm@marina.com.sa",
        hasBaseLine: false,
      },
      {
        id: "alqabas-paper-cardboard-printing",
        name: "مصنع القبس للمطبوعات الورقية والكرتونية",
        address: "منطقة القصيم",
        contactNumber: "966503983015",
        email: "qudis2017@fitinco.com",
        hasBaseLine: false,
      },
      {
        id: "al-itifaq-printing-press",
        name: "شركة مطبعة الاتفاق للطباعة على التغليف",
        address: "منطقة مكة المكرمة",
        contactNumber: "966541070909",
        email: "hr@alitifaq.net",
        hasBaseLine: false,
      },
      {
        id: "modern-printing-presses-ltd",
        name: "شركة المطابع العصرية المحدودة",
        address: "المنطقة الشرقية",
        contactNumber: "966555855579",
        email: "mamdouh.vehia@satech.com.sa",
        hasBaseLine: false,
      },
      {
        id: "awark-united-company-factory",
        name: "مصنع شركة أوارك المتحدة",
        address: "المنطقة الشرقية",
        contactNumber: "966567117825",
        email: "Hr@uarkprinting.com",
        hasBaseLine: false,
      },
      {
        id: "al-reem-printing-presses",
        name: "مطابع الريم للطباعة",
        address: "منطقة مكة المكرمة",
        contactNumber: "966534340793",
        email: "alreem.forprinting@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "al-tawfiq-printing-press",
        name: "مطبعة التوفيق للطباعة",
        address: "منطقة المدينة المنورة",
        contactNumber: "966555597875",
        email: "sohaanan@gmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 8,
    sectorCode: "25000000",
    name: "أكياس بلاستيكية",
    productCode: "25472902",
    sectorName: "المنتجات البلاستيكية",
    definition:
      "أكياس مصنوعة من البلاستيك هذا المنتج يشمل: اكياس بلاستيكية اكياس بلاستيكية عادية سادة ومطبوعة اكياس بولي ايثلين اكياس بلاستيكية للنفايات اكياس بلاستيكية عالية ومنخفضة الكثافة اكياس بولي ايثلين خدمات شاقة اكياس بلاستيكية مطبوعة مختلفة المقاسات",
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "المنتجات البلاستيكية - 25000000",
    subcategory: "أكياس بلاستيكية - 25472902",
    subcategory: "Aisle Marking Tape - 25002916",
    priceType: "Aqustiable",
    imageUrl: "/25472902.jpg",
    factories: [
      {
        id: "packaging-materials-manufacturing-co",
        name: "شركة تصنيع مواد التعبئة والتغليف",
        address: "الرياض",
        contactNumber: "966554292227",
        email: "Ayedm@fpctextile.com",
        hasBaseLine: false,
      },
      {
        id: "al-sharq-plastic-factories",
        name: "مصانع الشرق للبلاستيك",
        address: "الرياض",
        contactNumber: "966595557316",
        email: "ahmed@alsharqplastic.com.sa",
        hasBaseLine: false,
      },
      {
        id: "fipco-filling-packing-materials",
        name: "FIPCO Filling & Packing Materials",
        address: "منطقة الرياض",
        contactNumber: "966554292227",
        email: "ayedm@fpctextile.com",
        hasBaseLine: false,
      },
      {
        id: "al-sharq-plastic-factories-2",
        name: "مصانع الشرق للبلاستيك",
        address: "الرياض",
        contactNumber: "966595557316",
        email: "ahmed@alsharqplastic.com.sa",
        hasBaseLine: false,
      },
      {
        id: "packaging-materials-manufacturing-co-2",
        name: "شركة تصنيع مواد التعبئة والتغليف",
        address: "الرياض",
        contactNumber: "966554292227",
        email: "Ayedm@fpctextile.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 9,
    sectorCode: "19000000",
    name: "ملابس واقية من المواد الخطرة",
    productCode: "19002154",
    sectorName: "معدات ولوازم شخصية ومنزلية",
    definition: "ملابس مقاومة للقوس الكهربائي",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "معدات ولوازم شخصية ومنزلية - 19000000",
    subcategory: "ملابس واقية من المواد الخطرة - 19002154",
    priceType: "Aqustiable",
    imageUrl: "/19002154.png",
    factories: [
      {
        id: "alrafatex-clothing",
        name: "مصنع الرفاء للملابس",
        address: "المنطقة الشرقية",
        contactNumber: "966509800001",
        email: "nasser@alrafatex.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-textile-makkah",
        name: "السعودية لصناعة الأقمشة المحدودة",
        address: "منطقة مكة المكرمة",
        contactNumber: "966531392264",
        email: "abo-alwaled2020@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "global-stars-textiles",
        name: "مصنع همس النجوم للنسيج العالمي",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "hateem-cement-tiles",
        name: "...فلام حطيم المطبري لصناعة الأسمنة",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 10,
    sectorCode: "19000000",
    name: "خوذات سلامة",
    productCode: "19532502",
    sectorName: "معدات ولوازم شخصية ومنزلية",
    definition:
      "يتم تعريف هذا المنتج على أنه: الخوذ البلاستيكية المصممة لحماية الرأس من الإصابات",
    priceCeiling: 15,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "معدات ولوازم شخصية ومنزلية - 19000000",
    subcategory: "خوذات سلامة - 19532502",
    priceType: "Aqustiable",
    imageUrl: "/19532502.png",
    factories: [
      {
        id: "protective-equipment-company",
        name: "شركة معدات الحماية للصناعة",
        address: "الجائر منطقة الرياض",
        contactNumber: "966582291799",
        email: "almohsen@pef.com.sa",
        hasBaseLine: false,
      },
      {
        id: "protective-equipment-company-2",
        name: "شركة معدات الحماية للصناعة",
        address: "الجائر منطقة الرياض",
        contactNumber: "966582291799",
        email: "almohsen@pef.com.sa",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 11,
    sectorCode: "16000000",
    name: "مطهرات منزلية -رمز اعتماد3011",
    productCode: "16473011",
    sectorName: "مستهلكات النظافة",
    definition:
      "مواد كيميائية مصممة لتعطيل أو تدمير الكائنات الحية الدقيقة على الأسطح الخاملة. هذا البند يشمل: - المطهرات المضادة للبكتيريا - مطهرات الرائحة",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "مستهلكات النظافة - 16000000",
    subcategory: "مطهرات منزلية -رمز اعتماد3011 - 16473011",
    priceType: "Aqustiable",
    imageUrl: "/16473011.png",
    factories: [
      {
        id: "distinguished-banner-factory",
        name: "مصنع الراية المتميزة للصناعة",
        address: "منطقة مكة المكرمة",
        contactNumber: "966556603500",
        email: "hr.admin@asic.com.sa",
        hasBaseLine: false,
      },
      {
        id: "distinguished-banner-factory-2",
        name: "مصنع الراية المتميزة للصناعة",
        address: "منطقة مكة المكرمة",
        contactNumber: "966556603500",
        email: "hr.admin@asic.com.sa",
        hasBaseLine: false,
      },
      {
        id: "reza-investment-co-ltd",
        name: "شركة رضا للاستثمار المحدودة",
        address: "المدينة الصناعية، جدة",
        contactNumber: "966551021729",
        email: "sanjaya@rezagroup.com",
        hasBaseLine: false,
      },
      {
        id: "al-otian-restaurants-co",
        name: "شركات مطاعم العطيان مساهمة مقفلة",
        address: "منطقة الرياض",
        contactNumber: "966507946171",
        email: "amaly@rawabi.com.sa",
        hasBaseLine: false,
      },
      {
        id: "al-burji-cosmetics-factory",
        name: "مصنع البرجي لمستلزمات التجميل المحدوده",
        address: "الاسناد الرياضي، المدينة 3609",
        contactNumber: "6084444",
        email: "a.adel@batterjeeholding.com",
        hasBaseLine: false,
      },
      {
        id: "karnaf-chemical-products-factory",
        name: "مصنع كرنف للمنتجات الكيميائية",
        address: "Unnamed Road, 14326, الرياض",
        contactNumber: "12429000",
        email: "karnaffactory@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-energy-materials-production-co-factory",
        name: "مصنع الشركة السعودية لإنتاج مواد الطاقة",
        address: "المدينة الصناعية الثانية، 3616",
        contactNumber: "138166777",
        email: "gyr@sidco.com.sa",
        hasBaseLine: false,
      },
      {
        id: "safco-chemical-industries-factory",
        name: "مصنع صافكو للصناعات الكيميائية",
        address: "المدينة الصناعية الجديدة، 3147",
        contactNumber: "112650050",
        email: "Safcows@yahoo.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-energy-materials-production-co-factory-2",
        name: "مصنع الشركة السعودية لإنتاج مواد الطاقة",
        address: "المدينة الصناعية الثانية، 3616",
        contactNumber: "138166777",
        email: "gyr@sidco.com.sa",
        hasBaseLine: false,
      },
      {
        id: "hemam-wataneya-for-industry",
        name: "مصنع همم وطنية للصناعة",
        address: "المدينة الصناعية بالخرج",
        contactNumber: "506414045",
        email: "zaid4045@gamil.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 12,
    sectorCode: "18000000",
    name: "أعمدة",
    productCode: "18007016",
    sectorName: "الأثاث",
    definition: "أعمدة خشبية داخلية",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "الأثاث - 18000000",
    subcategory: "أعمدة - 18007016",
    priceType: "Aqustiable",
    imageUrl: "/18007016.png",
    factories: [
      {
        id: "batal-design-saudi-arabia",
        name: "شركة بطل ديزاين السعودية",
        address: "منطقة الرياض",
        contactNumber: "966506431891",
        email: "mohsenyam@bataldesign.com",
        hasBaseLine: false,
      },
      {
        id: "culture-factory-for-glass-facades",
        name: "مصنع الثقافة لصناعة الواجهات الزجاجية",
        address: "منطقة مكة المكرمة",
        contactNumber: "966500008300",
        email: "caravan_hr@yahoo.com",
        hasBaseLine: false,
      },
      {
        id: "the-distinctive-art-factory",
        name: "مصنع الفن المميز",
        address: "منطقة الرياض",
        contactNumber: "508627757",
        email: "info@upattern.com",
        hasBaseLine: false,
      },
      {
        id: "mabani-iron-wood-panels",
        name: "مصنع شركة المباني للالواح الحديدية و الخشبية",
        address: "-",
        contactNumber: "0",
        email: "-",
        hasBaseLine: false,
      },
      {
        id: "al-safratiya-wood-products",
        name: "شركة الصفراتية للمنتجات الخشبية",
        address: "منطقة الرياض",
        contactNumber: "966550889409",
        email: "n.shahbal@smsh.com.sa",
        hasBaseLine: false,
      },
      {
        id: "masterpieces-of-furniture-decor",
        name: "شركة روائع الأثاث للديكور",
        address: "منطقة مكة المكرمة",
        contactNumber: "966555339335",
        email: "A.QABANI@RWAYIE.COM",
        hasBaseLine: false,
      },
      {
        id: "asalah-industrial-assembly-factory",
        name: "مصنع مصنع شركة تجميع بأسلتة الصناعي",
        address: "منطقة القصيم",
        contactNumber: "966569752839",
        email: "sai@sultanah.com",
        hasBaseLine: false,
      },
      {
        id: "dana-palace-furniture-factory",
        name: "شركة مصنع دانة القصر لإنتاج الأثاث الخشبي",
        address: "منطقة الرياض",
        contactNumber: "966545566222",
        email: "Info@danapalace.com",
        hasBaseLine: false,
      },
      {
        id: "southern-gardens-furniture",
        name: "شركة أرى الحدائق الجنوبية لأثاث الخشبي",
        address: "منطقة مكة المكرمة",
        contactNumber: "966590907090",
        email: "a.z.g_444@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "palace-wood-trading-factory",
        name: "مصنع أخشاب القصر للتجارة",
        address: "-",
        contactNumber: "0",
        email: "-",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 13,
    sectorCode: "18000000",
    name: "ألواح تبطين خشبية",
    productCode: "18007017",
    sectorName: "الأثاث",
    definition: "الألواح الخشبية التي تبطن الجزء السفلي من جدران الغرفة",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "الأثاث - 18000000",
    subcategory: "ألواح تبطين خشبية - 18007017",
    priceType: "Aqustiable",
    imageUrl: "/18007017.png",
    factories: [
      {
        id: "beit-al-saadah-factory",
        name: "مصنع بيت السعادة للصناعة",
        address: "منطقة الرياض",
        contactNumber: "966505114366",
        email: "alsaeed66@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "alrabie-spring-factory",
        name: "مصنع تانية الربيع للصناعه",
        address: "منطقة الرياض",
        contactNumber: "966505233386",
        email: "sal4262@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "centimeter-wood-works-factory",
        name: "مصنع سنتيمتر للاعمال الخشبية",
        address: "منطقة الرياض",
        contactNumber: "504458000",
        email: "-",
        hasBaseLine: false,
      },
      {
        id: "international-expert-wood-industries",
        name: "شركة الخبرة الدولية للصناعات الخشبية",
        address: "منطقة مكة المكرمة",
        contactNumber: "966554442716",
        email: "admn.inex@gmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 14,
    sectorCode: "14000000",
    name: "المطبوعات – رمز اعتماد 4007",
    productCode: "14604007",
    sectorName: "ألأعمال الفنية",
    definition:
      'الصور التي يطبعها الفنان على الورق بنفسه أو تحت إشرافه باعتبارها إصدارًا جديداً من العمل الفني. ويشتمل تعريف المطبوعات على أساليب مختلفة من الطباعة مثل الصور الفوتوغرافية والحفر والطباعة على الشاشات. كما تجدر الإشارة إلى إمكانية طباعة عددٍ محدود من الإصدارات تحت مسمى " الإصدار الخاص أو المحدود" دون إمكانية طباعة إصدارات إضافية عنه في المستقبل. ويقوم الفنان عادة بتوقيع مطبوعات العمل الفني المنتَجة، وترقيم كل إصدار منها بتسلسله ضمن مجمل عدد المطبوعات. (على سبيل المثال: 1/ 100 ، 2/ 100 وهكذا).',
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "ألأعمال الفنية - 14000000",
    subcategory: "المطبوعات – رمز اعتماد 4007 - 14604007",
    priceType: "Aqustiable",
    imageUrl: "/14604007.jpg",
    factories: [
      {
        id: "laugure-art-gallery",
        name: "صالة لاجور للفنون",
        address: "جدة",
        contactNumber: "966507616203",
        email: "aelfaky@laugure.art",
        hasBaseLine: false,
      },
      {
        id: "athr-art-trading-company",
        name: "شركة أثر الفنية للتجارة",
        address: "جدة",
        contactNumber: "966557652512",
        email: "essam@athrart.com",
        hasBaseLine: false,
      },
      {
        id: "jada-ama-arts",
        name: "جادة أما الفنون",
        address: "الرياض",
        contactNumber: "966500092092",
        email: "ysossah@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "cube-art-gallery",
        name: "صالة تكعيب للفنون",
        address: "الرياض",
        contactNumber: "966554774436",
        email: "tamamys935@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "art-connection",
        name: "اتصال الفن",
        address: "الرياض",
        contactNumber: "966504402800",
        email: "nasseralkharyif@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "hafez-gallery",
        name: "حافظ جاليري",
        address: "جدة",
        contactNumber: "966559635106",
        email: "mohlkarar11@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "tafarod-art-space",
        name: "مساحة تفرد للفنون",
        address: "الأحساء",
        contactNumber: "966544180002",
        email: "kaltbaqshi@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "tala-art-gallery",
        name: "تالا ارت جاليري",
        address: "الرياض",
        contactNumber: "966537547929",
        email: "a.yamani@dallah.com",
        hasBaseLine: false,
      },
      {
        id: "sergey-art",
        name: "سيرجي ارت",
        address: "الرياض",
        contactNumber: "966555456784",
        email: "alia.aldigs@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "laugure-art-gallery-2",
        name: "صالة لاجور للفنون",
        address: "جدة",
        contactNumber: "966507616203",
        email: "aelfaky@laugure.art",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 15,
    sectorCode: "14000000",
    name: "الملصقات – رمز اعتماد 4008",
    productCode: "14604008",
    sectorName: "الاعمال الفنية",
    definition:
      "التصميمات أو النسخ الجذابة من اللوحات أو الصور الفوتوغرافية أو التصميمات. عادة ما يتم تصميم الملصقات باستخدام الصور والنصوص وإنتاجها بكميات كبيرة",
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "الاعمال الفنية - 14000000",
    subcategory: "الملصقات – رمز اعتماد 4008 - 14604008",
    priceType: "Aqustiable",
    imageUrl: "/14604008.png",
    factories: [
      {
        id: "tala-art-gallery",
        name: "تالا ارت جاليري",
        address: "الرياض",
        contactNumber: "533396880",
        email: "a.yamani@dallah.com",
        hasBaseLine: false,
      },
      {
        id: "sergey-art",
        name: "سيرجي ارت",
        address: "الرياض",
        contactNumber: "966555456784",
        email: "alia.aldigs@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "ahlam-gallery",
        name: "أحلام جاليري",
        address: "الرياض",
        contactNumber: "966503487078",
        email: "ahlam.studio.ksa@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "laugure-art-gallery",
        name: "صالة لاجور للفنون",
        address: "جدة",
        contactNumber: "966507616203",
        email: "aelfaky@laugure.art",
        hasBaseLine: false,
      },
      {
        id: "cube-art-gallery",
        name: "صالة تكعيب للفنون",
        address: "الرياض",
        contactNumber: "966554774436",
        email: "tamamys935@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "art-connection",
        name: "اتصال الفن",
        address: "الرياض",
        contactNumber: "966504402800",
        email: "nasseralkharji@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "hafez-gallery",
        name: "حافظ جاليري",
        address: "جدة",
        contactNumber: "966559635106",
        email: "mohlkarar11@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "tafarod-art-space",
        name: "مساحة تفرد للفنون",
        address: "الأحساء",
        contactNumber: "966544180002",
        email: "kaltbaqshi@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "tala-art-gallery-2",
        name: "تالا ارت جاليري",
        address: "الرياض",
        contactNumber: "966537547929",
        email: "a.yamani@dallah.com",
        hasBaseLine: false,
      },
      {
        id: "sergey-art-2",
        name: "سيرجي ارت",
        address: "الرياض",
        contactNumber: "966555456784",
        email: "alia.aldigs@gmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 16,
    sectorCode: "24000000",
    name: "معاجين السيارات",
    productCode: "24003108",
    sectorName: "النقل والخدمات اللوجستية",
    definition: "معجون يستخدم لسد الفراغات والخدوش في الهيكل الخارجي للسيارات",
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "النقل والخدمات اللوجستية - 24000000",
    subcategory: "معاجين السيارات - 24003108",
    priceType: "Aqustiable",
    imageUrl: "/24003108.jpg",
    factories: [
      {
        id: "makkah-paints-company",
        name: "شركة مكة للدهانات",
        address: "منطقة مكة المكرمة",
        contactNumber: "966555566270",
        email: "OMAR@AKA.COM.SA",
        hasBaseLine: false,
      },
      {
        id: "middle-east-paints-factory",
        name: "شركة مصنع الشرق الاوسط للدهانات",
        address: "منطقة مكة المكرمة",
        contactNumber: "966562512146",
        email: "a.shaker@mepaints.com",
        hasBaseLine: false,
      },
      {
        id: "jotun-saudi-arabia-ltd",
        name: "شركة جوتن السعودية المحدودة",
        address: "-",
        contactNumber: "0",
        email: "-",
        hasBaseLine: false,
      },
    ],
  },
];
