export const featuredProducts = [
  {
    id: 1,
    sectorCode: "20000000",
    name: "Paper Table Cloth",
    productCode: "20002608",
    sectorName: "Paper Consumer Products",
    definition:
      "This product includes: *Paper, a kind prepared for usage and towels and similar paper for sanitary purposes. *Paper, a kind prepared for usage and similar paper for household purposes *Paper, a kind prepared for usage and to wels and similar paper for sanitary purposes *Protective coverings for hospital beds to absorb excretion.",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 27 ديسمبر 2025",
    category: "Paper Consumer Products - 20000000",
    subcategory: "Paper Table Cloth - 20002608",
    priceType: "Aqustiable",
    imageUrl: "/20002608.jpg",
    factories: [],
  },
  {
    id: 2,
    sectorCode: "20000000",
    name: "Facial Tissues",
    productCode: "20002610",
    sectorName: "Paper Consumer Products",
    definition:
      "This product includes: toilet paper Tissue paper and towels (rolls) Scented and unscented wipes Others",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 27 ديسمبر 2025",
    category: "Paper Consumer Products - 20000000",
    subcategory: "Facial Tissues - 20002610",
    priceType: "Aqustiable",
    imageUrl: "/20002610.png",
    factories: [],
  },
  {
    id: 3,
    sectorCode: "11000000",
    name: "Universal Joints",
    productCode: "11002190",
    sectorName: "Construction and Building Materials",
    definition:
      "Heat-shrink sealed connectors, used to connect electrical cables to each other",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 24/6/2025",
    category: "Construction and Building Materials - 11000000",
    subcategory: "Universal Joints - 11002190",
    priceType: "Aqustiable",
    imageUrl: "/11002190.png",
    factories: [
      {
        id: "erga-fertilizers-ltd",
        name: "شركة ايرقا لصناعة الأسمدة المحدودة",
        address: "منطقة الرياض",
        contactNumber: "966559777667",
        email: "Ahmeda@aljardan.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 4,
    sectorCode: "20000000",
    name: "PVC plastic Pipe Elbow",
    productCode: "11002204",
    sectorName: "Construction and Building Materials",
    definition:
      "Ductile iron fittings are widely used in various industrial and construction applications",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 1 سبتمبر 2025",
    category: "Paper Consumer Products - 20000000",
    subcategory: "PVC plastic Pipe Elbow - 11002204",
    priceType: "Aqustiable",
    imageUrl: "/11002204.png",
    factories: [
      {
        id: "saudi-pipe-systems-company",
        name: "SAUDI PIPE SYSTEMS COMPANY",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "lemon-industrial",
        name: "مصنع شركة دلمون للعوازل الصناعية والميكانيكية",
        address: "المنطقة الشرقية",
        contactNumber: "966553665200",
        email: "islamhammad@delmon.com.sa",
        hasBaseLine: false,
      },
      {
        id: "future-pipes",
        name: "شركة صناعة أنابيب المستقبل المحدودة",
        address: "المنطقة الشرقية",
        contactNumber: "966562803337",
        email: "M.Jazeri@futurepipe.com",
        hasBaseLine: false,
      },
      {
        id: "pipes-and-iron",
        name: "مصنع الدقة لصناعة الفلنجات ولوازم الانابيب و المشغولات الحديدية",
        address: "المنطقة الشرقية",
        contactNumber: "966508252965",
        email: "pff_administration@alsuwaidi.com",
        hasBaseLine: false,
      },
      {
        id: "gulf-factory",
        name: "شركة مصنع الخليج للأعمال المتخصصة",
        address: "المنطقة الشرقية",
        contactNumber: "966555807639",
        email: "yousif.basher@pangulfsteel",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 5,
    sectorCode: "17000000",
    name: "Paint Thinner",
    productCode: "17006020",
    sectorName: "Chemical and Fertilizers",
    definition: "A chemical product used to dissolove exterior paint in cars",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "Chemical and Fertilizers - 17000000",
    subcategory: "Paint Thinner - 17006020",
    priceType: "Aqustiable",
    imageUrl: "/17006020.jpg",
    factories: [
      {
        id: "makkah-paints",
        name: "شركة مكة للدهانات",
        address: "منطقة مكة المكرمة",
        contactNumber: "966555566270",
        email: "OMAR@AKA.COM.SA",
        hasBaseLine: false,
      },
      {
        id: "lemon-industrial",
        name: "مصنع شركة سيجما السعودية للدهانات المحدودة",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "dammam-gates",
        name: "مصنع بوابة الدمام للدهانات",
        address: "المنطقة الشرقية",
        contactNumber: "966505178923",
        email: "h.dgf@hotmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 6,
    sectorCode: "17000000",
    name: "Alcohol Solvents",
    productCode: "17006025",
    sectorName: "Chemical and Fertilizers",
    definition:
      "The organic solvents that contain alcohol as a functional group. These solvents are used for cleaning, dissolving, and dispersing various substances in industries such as pharmaceuticals, paints, and coatings.",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 1 سبتمبر 2025",
    category: "Chemical and Fertilizers - 17000000",
    subcategory: "Alcohol Solvents - 17006025",
    priceType: "Aqustiable",
    imageUrl: "/17006025.jpg",
    factories: [
      {
        id: "arabian-pipe-coating",
        name: "Arabian Pipe Coating Company",
        address: "****",
        contactNumber: "966",
        email: "****",
        hasBaseLine: false,
      },
      {
        id: "apco-coating-eastern",
        name: "فرع الشركة العربية لتغليف الأنابيب",
        address: "المنطقة الشرقية",
        contactNumber: "966560043098",
        email: "mababneh@apco-coating.com",
        hasBaseLine: false,
      },
      {
        id: "khodair-pipes",
        name: "وحدة إطلاق أنابيب الأسلاك الكهربائية",
        address: "المنطقة الشرقية",
        contactNumber: "966541520859",
        email: "mohammed.al-khodair@s3c....",
        hasBaseLine: false,
      },
      {
        id: "oriental-coatings",
        name: "... إطلاق الشرق للدهانات والعلاجات",
        address: "منطقة الرياض",
        contactNumber: "966504441840",
        email: "suul97@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "tamyeez-chemicals",
        name: "مصنع ريبون للكيماويات",
        address: "المنطقة الشرقية",
        contactNumber: "966505856268",
        email: "abdullah@tamyeez.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 7,
    sectorCode: "25000000",
    name: "Food Service Table Covering Rolls",
    productCode: "25472906",
    sectorName: "Plastic Consumer Products",
    definition:
      "It's a covering spread made from Plastics over a dining table before the tableware is set",
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "Plastic Consumer Products - 25000000",
    subcategory: "Food Service Table Covering Rolls - 25472906",
    priceType: "Aqustiable",
    imageUrl: "/25472906.jpg",
    factories: [],
  },
  {
    id: 8,
    sectorCode: "25000000",
    name: "Aisle Marking Tape",
    productCode: "25002916",
    sectorName: "Plastic Products",
    definition:
      'Barricade tape is brightly colored tape (often incorporating a two-tone pattern of alternating yellow-black or red-white stripes or the words "Caution" or "Danger" in prominent lettering) that is used to warn or catch the attention of passersby of an area or situation containing a possible hazard.',
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "Plastic Consumer Products - 25000000",
    subcategory: "Aisle Marking Tape - 25002916",
    priceType: "Aqustiable",
    imageUrl: "/25002916.jpg",
    factories: [],
  },
  {
    id: 9,
    sectorCode: "19000000",
    name: "Hazardous Material Protective Apparel",
    productCode: "19002154",
    sectorName: "Safety and Security Equipment",
    definition: "ARC Flash Protection Uniforms",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "Safety and Security Equipment - 19000000",
    subcategory: "Hazardous Material Protective Apparel - 19002154",
    priceType: "Aqustiable",
    imageUrl: "/19002154.png",
    factories: [
      {
        id: "alrafatex-clothing",
        name: "مصنع الرفاء للملابس",
        address: "المنطقة الشرقية",
        contactNumber: "966509800001",
        email: "nasser@alrafatex.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-textile-makkah",
        name: "السعودية لصناعة الأقمشة المحدودة",
        address: "منطقة مكة المكرمة",
        contactNumber: "966531392264",
        email: "abo-alwaled2020@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "global-stars-textiles",
        name: "مصنع همس النجوم للنسيج العالمي",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "hateem-cement-tiles",
        name: "...فلام حطيم المطبري لصناعة الأسمنة",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 10,
    sectorCode: "19000000",
    name: "Safety Helmets",
    productCode: "19532502",
    sectorName: "Safety and Security Equipment",
    definition:
      "This product is defined as: Plastic helmet designed to protect the head from accidental injury",
    priceCeiling: 15,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "Safety and Security Equipment - 19000000",
    subcategory: "Safety Helmets - 19532502",
    priceType: "Aqustiable",
    imageUrl: "/19532502.png",
    factories: [
      {
        id: "protective-equipment-company",
        name: "شركة معدات الحماية للصناعة",
        address: "الجائر منطقة الرياض",
        contactNumber: "966582291799",
        email: "almohsen@pef.com.sa",
        hasBaseLine: false,
      },
      {
        id: "protective-equipment-company-2",
        name: "شركة معدات الحماية للصناعة",
        address: "الجائر منطقة الرياض",
        contactNumber: "966582291799",
        email: "almohsen@pef.com.sa",
        hasBaseLine: false,
      },
    ],
  },
];
