export const featuredProducts = [
  {
    id: 1,
    sectorCode: "20000000",
    name: "غطاء طاولة ورقي",
    productCode: "20002608",
    sectorName: "المنتجات الاستهلاكية الورقية",
    definition:
      "هذا المنتج يشمل : - ورق من النوع المعد للاستعمال كورق لمناشف المائدة، -ورق من النوع المعد للاستعمال والأوراق المماثلة للاستعمالات المنزلية . -ورق من النوع المعد للاستعمال والمناشف والأوراق المماثلة للاستعمالات الصحية . -أغطية واقية لأسرة المستشفيات لإمتصاص الإفرازات .",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 27 ديسمبر 2025",
    category: "المنتجات الاستهلاكية الورقية - 20000000",
    subcategory: "غطاء طاولة ورقي - 20002608",
    priceType: "Aqustiable",
    imageUrl: "/20002608.jpg",
    factories: [],
  },
  {
    id: 2,
    sectorCode: "20000000",
    name: "مناديل وجه",
    productCode: "20002610",
    sectorName: "المنتجات الاستهلاكية الورقية",
    definition:
      "هذا المنتج يشمل : - مناديل ورقية للحمامات -ورق مناديل ومناشف (لفات) -مناديل معطرة وغير معطرة -وغيرها",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 27 ديسمبر 2025",
    category: "المنتجات الاستهلاكية الورقية - 20000000",
    subcategory: "مناديل وجه - 20002610",
    priceType: "Aqustiable",
    imageUrl: "/20002610.png",
    factories: [],
  },
  {
    id: 3,
    sectorCode: "11000000",
    name: "وصلات ميكانية",
    productCode: "11002190",
    sectorName: "البناء والتشييد",
    definition:
      "وصلات غالقة منكمشة بالحرارة، تستخدم في توصيل الكلابلات الكهربائية مع بعضها البعض",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 24/6/2025",
    category: "البناء والتشييد - 11000000",
    subcategory: "وصلات ميكانية - 11002190",
    priceType: "Aqustiable",
    imageUrl: "/11002190.png",
    factories: [
      {
        id: "erga-fertilizers-ltd",
        name: "شركة ايرقا لصناعة الأسمدة المحدودة",
        address: "منطقة الرياض",
        contactNumber: "966559777667",
        email: "Ahmeda@aljardan.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 4,
    sectorCode: "11000000",
    name: "11002204",
    productCode: "11002204",
    sectorName: "البناء والتشييد",
    definition:
      "مسبار تشبع المستشعر (لجهاز قياس التأكسج النبضي) لاصق بأطراف الأصابع، أقل من 3 كجم، يمكن التخلص منه، متوافق مع نظام أوكسيماكس نيلكور أو ما يعادله.",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 1 سبتمبر 2025",
    category: "البناء والتشييد - 11000000",
    subcategory: "11002204 - 11002204",
    priceType: "Aqustiable",
    imageUrl: "/11002204.png",
    factories: [
      {
        id: "saudi-pipe-systems-company",
        name: "SAUDI PIPE SYSTEMS COMPANY",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "lemon-industrial",
        name: "مصنع شركة دلمون للعوازل الصناعية والميكانيكية",
        address: "المنطقة الشرقية",
        contactNumber: "966553665200",
        email: "islamhammad@delmon.com.sa",
        hasBaseLine: false,
      },
      {
        id: "future-pipes",
        name: "شركة صناعة أنابيب المستقبل المحدودة",
        address: "المنطقة الشرقية",
        contactNumber: "966562803337",
        email: "M.Jazeri@futurepipe.com",
        hasBaseLine: false,
      },
      {
        id: "pipes-and-iron",
        name: "مصنع الدقة لصناعة الفلنجات ولوازم الانابيب و المشغولات الحديدية",
        address: "المنطقة الشرقية",
        contactNumber: "966508252965",
        email: "pff_administration@alsuwaidi.com",
        hasBaseLine: false,
      },
      {
        id: "gulf-factory",
        name: "شركة مصنع الخليج للأعمال المتخصصة",
        address: "المنطقة الشرقية",
        contactNumber: "966555807639",
        email: "yousif.basher@pangulfsteel",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 5,
    sectorCode: "17000000",
    name: "مذيب دهان",
    productCode: "17006020",
    sectorName: "المواد الكيميائية و الأسمدة",
    definition: "منتج كيميائي يستخدم في اذابة الدهان الخارجي للسيارات وغيرها",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "المواد الكيميائية و الأسمدة - 17000000",
    subcategory: "مذيب دهان - 17006020",
    priceType: "Aqustiable",
    imageUrl: "/17006020.jpg",
    factories: [
      {
        id: "makkah-paints",
        name: "شركة مكة للدهانات",
        address: "منطقة مكة المكرمة",
        contactNumber: "966555566270",
        email: "OMAR@AKA.COM.SA",
        hasBaseLine: false,
      },
      {
        id: "lemon-industrial",
        name: "مصنع شركة سيجما السعودية للدهانات المحدودة",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "dammam-gates",
        name: "مصنع بوابة الدمام للدهانات",
        address: "المنطقة الشرقية",
        contactNumber: "966505178923",
        email: "h.dgf@hotmail.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 6,
    sectorCode: "17000000",
    name: "طلاء الايبوكسي المطابق",
    productCode: "17006025",
    sectorName: "المواد الكيميائية و الأسمدة",
    definition: "لا يوجد",
    priceCeiling: 30,
    localContentCertificate:
      "يشترط وجود شهادة المحتوى المحلي للمصنع اعتبارا من تاريخ 1 سبتمبر 2025",
    category: "المواد الكيميائية و الأسمدة - 17000000",
    subcategory: "طلاء الايبوكسي المطابق - 17006025",
    priceType: "Aqustiable",
    imageUrl: "/17006025.jpg",
    factories: [
      {
        id: "arabian-pipe-coating",
        name: "Arabian Pipe Coating Company",
        address: "****",
        contactNumber: "966",
        email: "****",
        hasBaseLine: false,
      },
      {
        id: "apco-coating-eastern",
        name: "فرع الشركة العربية لتغليف الأنابيب",
        address: "المنطقة الشرقية",
        contactNumber: "966560043098",
        email: "mababneh@apco-coating.com",
        hasBaseLine: false,
      },
      {
        id: "khodair-pipes",
        name: "وحدة إطلاق أنابيب الأسلاك الكهربائية",
        address: "المنطقة الشرقية",
        contactNumber: "966541520859",
        email: "mohammed.al-khodair@s3c....",
        hasBaseLine: false,
      },
      {
        id: "oriental-coatings",
        name: "... إطلاق الشرق للدهانات والعلاجات",
        address: "منطقة الرياض",
        contactNumber: "966504441840",
        email: "suul97@gmail.com",
        hasBaseLine: false,
      },
      {
        id: "tamyeez-chemicals",
        name: "مصنع ريبون للكيماويات",
        address: "المنطقة الشرقية",
        contactNumber: "966505856268",
        email: "abdullah@tamyeez.com",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 7,
    sectorCode: "25000000",
    name: "لفافات لتغطية المائدة",
    productCode: "25472906",
    sectorName: "المنتجات الاستهلاكية البلاستيكية",
    definition:
      "غطاء مصنوع من البلاستيك يتم وضعه فوق طاولة الطعام قبل وضع أدوات المائدة",
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "المنتجات الاستهلاكية البلاستيكية - 25000000",
    subcategory: "لفافات لتغطية المائدة - 25472906",
    priceType: "Aqustiable",
    imageUrl: "/25472906.jpg",
    factories: [],
  },
  {
    id: 8,
    sectorCode: "25000000",
    name: "شريط تميز الممرات",
    productCode: "25002916",
    sectorName: "المنتجات الاستهلاكية و البلاستيكية",
    definition:
      'شريط التحذير هو شريط ذو ألوان زاهية (غالبًا ما يتضمن نمطًا ثنائي اللون من خطوط باللون الأصفر والأسود أو الأحمر والأبيض بالتناوب أو الكلمات "تحذير" أو "خطر" في حروف بارزة) يُستخدم لتحذير المارة أو جذب انتباههم منطقة أو موقف يحتوي على خطر محتمل.',
    priceCeiling: 10,
    localContentCertificate: "لا يشترط وجود شهادة المحتوى المحلي",
    category: "المنتجات الاستهلاكية و البلاستيكية - 25000000",
    subcategory: "شريط تميز الممرات - 25002916",
    priceType: "Aqustiable",
    imageUrl: "/25002916.jpg",
    factories: [],
  },
  {
    id: 9,
    sectorCode: "19000000",
    name: "ملابس واقية من المواد الخطرة",
    productCode: "19002154",
    sectorName: "معدات ولوازم شخصية ومنزلية",
    definition: "ملابس مقاومة للقوس الكهربائي",
    priceCeiling: 10,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "معدات ولوازم شخصية ومنزلية - 19000000",
    subcategory: "ملابس واقية من المواد الخطرة - 19002154",
    priceType: "Aqustiable",
    imageUrl: "/19002154.png",
    factories: [
      {
        id: "alrafatex-clothing",
        name: "مصنع الرفاء للملابس",
        address: "المنطقة الشرقية",
        contactNumber: "966509800001",
        email: "nasser@alrafatex.com",
        hasBaseLine: false,
      },
      {
        id: "saudi-textile-makkah",
        name: "السعودية لصناعة الأقمشة المحدودة",
        address: "منطقة مكة المكرمة",
        contactNumber: "966531392264",
        email: "abo-alwaled2020@hotmail.com",
        hasBaseLine: false,
      },
      {
        id: "global-stars-textiles",
        name: "مصنع همس النجوم للنسيج العالمي",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
      {
        id: "hateem-cement-tiles",
        name: "...فلام حطيم المطبري لصناعة الأسمنة",
        address: "***",
        contactNumber: "***",
        email: "***",
        hasBaseLine: false,
      },
    ],
  },
  {
    id: 10,
    sectorCode: "19000000",
    name: "خوذات سلامة",
    productCode: "19532502",
    sectorName: "معدات ولوازم شخصية ومنزلية",
    definition:
      "يتم تعريف هذا المنتج على أنه: الخوذ البلاستيكية المصممة لحماية الرأس من الإصابات",
    priceCeiling: 15,
    localContentCertificate: "يشترط وجود شهادة المحتوى المحلي للمصنع",
    category: "معدات ولوازم شخصية ومنزلية - 19000000",
    subcategory: "خوذات سلامة - 19532502",
    priceType: "Aqustiable",
    imageUrl: "/19532502.png",
    factories: [
      {
        id: "protective-equipment-company",
        name: "شركة معدات الحماية للصناعة",
        address: "الجائر منطقة الرياض",
        contactNumber: "966582291799",
        email: "almohsen@pef.com.sa",
        hasBaseLine: false,
      },
      {
        id: "protective-equipment-company-2",
        name: "شركة معدات الحماية للصناعة",
        address: "الجائر منطقة الرياض",
        contactNumber: "966582291799",
        email: "almohsen@pef.com.sa",
        hasBaseLine: false,
      },
    ],
  },
];
